development: &default
  adapter: postgresql
  database: lawgix_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000

test:
  <<: *default
  database: lawgix_test

staging:
  <<: *default
  database: lawgix_staging

production:
  <<: *default
  database: lawgix
