require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TitleAbstractsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # TitleAbstract. As you add validations to TitleAbstract, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes){  FactoryGirl.build(:title_abstract).attributes.symbolize_keys }

  # let(:invalid_attributes) {
  #   skip("Add a hash of attributes invalid for your model")
  # }
  #
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TitleAbstractsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all title_abstracts as @title_abstracts" do
      title_abstract = TitleAbstract.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:title_abstracts)).to eq([title_abstract])
    end
  end

  describe "GET show" do
    it "assigns the requested title_abstract as @title_abstract" do
      title_abstract = TitleAbstract.create! valid_attributes
      get :show, {:id => title_abstract.to_param}, valid_session
      expect(assigns(:title_abstract)).to eq(title_abstract)
    end
  end

  describe "GET new" do
    it "assigns a new title_abstract as @title_abstract" do
      get :new, {}, valid_session
      expect(assigns(:title_abstract)).to be_a_new(TitleAbstract)
    end
  end

  describe "GET edit" do
    it "assigns the requested title_abstract as @title_abstract" do
      title_abstract = TitleAbstract.create! valid_attributes
      get :edit, {:id => title_abstract.to_param}, valid_session
      expect(assigns(:title_abstract)).to eq(title_abstract)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TitleAbstract" do
        expect {
          post :create, {:title_abstract => valid_attributes}, valid_session
        }.to change(TitleAbstract, :count).by(1)
      end

      it "assigns a newly created title_abstract as @title_abstract" do
        post :create, {:title_abstract => valid_attributes}, valid_session
        expect(assigns(:title_abstract)).to be_a(TitleAbstract)
        expect(assigns(:title_abstract)).to be_persisted
      end

      it "redirects to the created title_abstract" do
        post :create, {:title_abstract => valid_attributes}, valid_session
        expect(response).to redirect_to(TitleAbstract.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved title_abstract as @title_abstract" do
        post :create, {:title_abstract => invalid_attributes}, valid_session
        expect(assigns(:title_abstract)).to be_a_new(TitleAbstract)
      end

      it "re-renders the 'new' template" do
        post :create, {:title_abstract => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested title_abstract" do
        title_abstract = TitleAbstract.create! valid_attributes
        put :update, {:id => title_abstract.to_param, :title_abstract => new_attributes}, valid_session
        title_abstract.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested title_abstract as @title_abstract" do
        title_abstract = TitleAbstract.create! valid_attributes
        put :update, {:id => title_abstract.to_param, :title_abstract => valid_attributes}, valid_session
        expect(assigns(:title_abstract)).to eq(title_abstract)
      end

      it "redirects to the title_abstract" do
        title_abstract = TitleAbstract.create! valid_attributes
        put :update, {:id => title_abstract.to_param, :title_abstract => valid_attributes}, valid_session
        expect(response).to redirect_to(title_abstract)
      end
    end

    describe "with invalid params" do
      it "assigns the title_abstract as @title_abstract" do
        title_abstract = TitleAbstract.create! valid_attributes
        put :update, {:id => title_abstract.to_param, :title_abstract => invalid_attributes}, valid_session
        expect(assigns(:title_abstract)).to eq(title_abstract)
      end

      it "re-renders the 'edit' template" do
        title_abstract = TitleAbstract.create! valid_attributes
        put :update, {:id => title_abstract.to_param, :title_abstract => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested title_abstract" do
      title_abstract = TitleAbstract.create! valid_attributes
      expect {
        delete :destroy, {:id => title_abstract.to_param}, valid_session
      }.to change(TitleAbstract, :count).by(-1)
    end

    it "redirects to the title_abstracts list" do
      title_abstract = TitleAbstract.create! valid_attributes
      delete :destroy, {:id => title_abstract.to_param}, valid_session
      expect(response).to redirect_to(title_abstracts_url)
    end
  end

end
